package dev.vox.lss.paper;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.fail;

/**
 * 1.21.11-LINE fixture regenerator for the frozen {@code nbt-corpus} NATIVE fixtures —
 * Paper twin of the Fabric {@code NativeCorpusRegenTool}: rewrites each as
 * {@code fromV20(v20-corpus twin)} through THIS module's production registry tables,
 * under the standard {@code LSS_REGEN_GOLDENS} discipline (a normal test run returns
 * without touching anything). Native bytes are registry-coupled (DIRECT longs and
 * indexed palettes embed numeric registry ids) AND count-short-shaped per line/platform
 * (Paper's Moonrise recalc drops the fluid term this line's vanilla folds in), so the
 * v20 twins are the regeneration source of truth. Skips {@code duplicate-air.bin}
 * (fromV20 collapses its deliberate duplicate palette — converted once at the re-port
 * by a byte-level fold instead) and {@code xray-masked.bin} (regenerated by the
 * mask-filter golden test).
 */
class NativeCorpusRegenTool {

    static {
        net.minecraft.SharedConstants.tryDetectVersion();
        net.minecraft.server.Bootstrap.bootStrap();
    }

    @Test
    void regenerateNativeCorpusFromV20() throws Exception {
        if (!"true".equalsIgnoreCase(System.getenv("LSS_REGEN_GOLDENS"))) {
            return;
        }
        Path dir = Path.of("").toAbsolutePath();
        Path module = null;
        for (int depth = 0; depth < 5 && dir != null; depth++, dir = dir.getParent()) {
            if (Files.isDirectory(dir.resolve("src/test/java/dev/vox/lss"))) { module = dir; break; }
            if (Files.isDirectory(dir.resolve("paper/src/test/java/dev/vox/lss"))) { module = dir.resolve("paper"); break; }
        }
        if (module == null) throw new IllegalStateException("cannot locate module tree");
        Path v20Dir = module.resolve("src/test/resources/v20-corpus");
        Path nativeDir = module.resolve("src/test/resources/nbt-corpus");
        var registryAccess = CorpusRegistryAccess.build();
        StringBuilder wrote = new StringBuilder();
        try (var files = Files.list(v20Dir)) {
            for (Path p : files.sorted().toList()) {
                String name = p.getFileName().toString();
                if (!name.endsWith(".bin")) continue;
                if (name.equals("duplicate-air.bin") || name.equals("xray-masked.bin")) continue;
                byte[] nativeBytes = PaperNbtSectionSerializer.fromV20(Files.readAllBytes(p), registryAccess);
                Files.write(nativeDir.resolve(name), nativeBytes);
                wrote.append(name).append(' ');
            }
        }
        fail("native corpus regenerated (" + wrote + "), re-run without LSS_REGEN_GOLDENS and commit the fixtures");
    }
}
